# docker-compose.yml
# Experimental does not work. Was to lazy to make it work, because
# the Makefile works so well. Feel free to make it work.
version: '3'

services:
  deno:
    image: ubuntu:18.04
    restart: "no"
    volumes:
      - ./deno_linux_x64:/bin/deno
      - ../src:/data
    entrypoint: "/bin/deno --allow-read /data/mod.ts"
